# Generated by Django 3.1.6 on 2021-12-07 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=50, unique=True)),
                ('is_employee', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_manager', models.BooleanField(default=False)),
                ('first_name', models.TextField(max_length=50)),
                ('last_name', models.TextField(max_length=50)),
                ('dob', models.DateField()),
                ('department_code', models.TextField(max_length=10)),
                ('phone_number', models.TextField(max_length=10)),
                ('leave_balance', models.IntegerField(default=30)),
                ('joining_date', models.DateField()),
                ('online', models.BooleanField(verbose_name=True)),
            ],
        ),
    ]
