# Generated by Django 3.1.6 on 2021-12-07 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='department_code',
            field=models.TextField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='joining_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='leave_balance',
            field=models.IntegerField(default=30, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='online',
            field=models.BooleanField(null=True, verbose_name=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='phone_number',
            field=models.TextField(max_length=10, null=True),
        ),
    ]
