# Generated by Django 3.1.6 on 2021-12-14 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20211209_0730'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='admin',
            field=models.TextField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='manager',
            field=models.TextField(default='', max_length=50),
        ),
    ]
