# Generated by Django 3.1.6 on 2021-12-18 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20211214_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
