# Generated by Django 3.1.6 on 2021-12-20 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userdetails_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='contract_based',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='regular_based',
            field=models.BooleanField(default=False),
        ),
    ]
