# Generated by Django 3.1.6 on 2021-12-20 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20211220_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='leaves_month',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='leaves_total',
            field=models.IntegerField(default=0),
        ),
    ]
