# Generated by Django 3.1.6 on 2022-04-22 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20211220_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
    ]
