# Generated by Django 3.1.6 on 2022-02-19 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0008_auto_20211220_2151'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('seen', models.BooleanField(default=False)),
                ('_from', models.TextField(max_length=50)),
                ('description', models.TextField(max_length=100)),
                ('_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userdetails')),
            ],
        ),
    ]
