# Generated by Django 3.1.6 on 2021-12-09 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.TextField(max_length=50)),
                ('employee', models.TextField(max_length=50)),
                ('manager', models.TextField(max_length=50)),
                ('admin', models.TextField(max_length=50)),
                ('applied_on', models.DateField(auto_now_add=True)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('number_of_days', models.IntegerField()),
                ('purpose', models.TextField(max_length=100)),
                ('address_during_leave', models.TextField(max_length=100)),
                ('status', models.TextField(max_length=50)),
            ],
        ),
    ]
