# Generated by Django 3.1.6 on 2021-12-15 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0003_leave_leave_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='leave_id',
        ),
    ]
