# Generated by Django 3.1.6 on 2021-12-17 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0004_remove_leave_leave_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='admin_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leave',
            name='manager_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leave',
            name='waiting_approval',
            field=models.BooleanField(default=True),
        ),
    ]
