# Generated by Django 3.1.6 on 2021-12-20 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0006_leave_manager_rejected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='applied_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
