# Generated by Django 3.1.6 on 2021-12-20 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
