# Generated by Django 3.1.6 on 2022-04-27 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leaves', '0007_auto_20211220_2328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_from', models.TextField(max_length=10)),
                ('msg', models.TextField(max_length=200)),
                ('send_on', models.DateTimeField(auto_now_add=True)),
                ('seen', models.BooleanField(default=False)),
                ('leave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaves.leave')),
            ],
        ),
    ]
