# Generated by Django 3.1.6 on 2021-12-20 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_types', '0002_auto_20211220_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavetype',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
