# Generated by Django 3.1.6 on 2022-02-19 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_types', '0003_auto_20211220_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='limit',
            field=models.IntegerField(null=True),
        ),
    ]
